config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'

  resources :patients
  get 'summary/:id', to: 'patients#summary', as: :summary
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_one :admission
  has_many :allergies
  has_many :medication_orders
  has_many :diagnostic_procedures
  has_many :diagnoses
  has_many :treatments

  enum gender: [:male, :female, :other]

  validates :first_name, :last_name, :medical_record, :birth_date, :gender, presence: true

  validates :admission, presence: true
  validates :allergies, presence: true
  validates :medication_orders, presence: true
  validates :diagnostic_procedures, presence: true
  validates :diagnoses, presence: true
  validates :treatments, presence: true

  def age
    0 if birth_date.blank?
    now = Time.now.utc.to_date
    now.year - birth_date.year - (now.month > birth_date.month || (now.month == birth_date.month && now.day >= birth_date.day) ? 0 : 1)
  end

  def simple_diagnoses
    diagnoses.where is_chronic_condition: false
  end

  def chronic_conditions
    diagnoses.where is_chronic_condition: true
  end

  def full_name
    "#{first_name} #{middle_name} #{last_name}"
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :breadcrumbs
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  def index
    @patients = Patient.all
  end

  def summary
    @facility = Facility.first
    @patient = Patient.find(params[:id])
  end

  private

  def record_not_found
    flash[:error] = 'Patient not found'
    redirect_to patients_path
  end

  def breadcrumbs
    @breadcrumbs = [{ label: 'Patients' }]
    @breadcrumbs << { label: 'Summary' } if params[:action] == 'summary'
  end
end

app/helpers/patients_helper.rb
module PatientsHelper
  def render_medications(medication_orders)
    medications = []
    medication_orders.each do |order|
      medications << "#{order.name} #{order.dosage}#{t("enums.mass_unit.#{order.unit}")} #{t("enums.routes.#{order.route}")} #{order.frequency.order_frequency_value}#{t("enums.frequency_unit.#{order.frequency.unit}")} to #{order.necessity}"
    end
    medications.to_sentence
  end

  def render_diagnostic_procedures(diagnostic_procedures)
    procedures = []
    diagnostic_procedures.each do |procedure|
      procedures << "#{procedure.description} #{l(procedure.moment, format: :hours)}"
    end
    procedures.to_sentence
  end

  def render_patient_summary(facility, patient)
    html = ''
    html << %(<p>)
    html << %(This #{patient.age} years old #{patient.gender} was admitted to #{facility.name}\ )
    html << %(on #{l(patient.admission.moment, format: :complete)}\ )
    html << %(due to #{patient.admission.diagnoses.map(&:described_code).to_sentence}.\ )
    html << %(The observed symptoms on admission were #{patient.admission.symptoms.map(&:description).to_sentence}.\ )
    html << %(#{patient.admission.observations.map(&:description).to_sentence}.)
    html << %(</p>)

    html << %(<p>)
    html << %(Upon asking about known allergies, the patient disclosed #{patient.allergies.map(&:description).to_sentence}.\ )
    html << %(Upon asking about chronic conditions, the patient disclosed\ )
    html << %(#{patient.chronic_conditions.map(&:described_code).to_sentence}.\ )
    html << %(The patient was administered with #{render_medications(patient.medication_orders)}.)
    html << %(</p>)

    html << %(<p>)
    html << %(The staff performed #{render_diagnostic_procedures(patient.diagnostic_procedures)},\ )
    html << %(revealing #{patient.simple_diagnoses.map(&:described_code).to_sentence}.\ )
    html << %(Our team proceeded to #{patient.treatments.map(&:described_treatment).to_sentence}.\ )
    html << %(</p>)

    html.html_safe
  end
end

app/views/patients/_form.html.erb
<div class="row">
  <div class="col-md-12 col-lg-12 col-sm-12">
    <%= form_for patient, url: url, method: method_type, remote: remote do |form| -%>
    <p class="lead">Patient data</p>
    <% unless patient.id.nil? -%>
    <div class="row">
      <div class="col-md-12">
        <div class="form-group">
          <label class="control-label">ID</label>
          <p class="form-control-static"><%= patient.id -%></p>
        </div>
      </div>
    </div>
    <% end %>
    <div class="row">
      <div class="col-md-12">
        <div class="form-group">
          <label class="control-label">First Name</label>
          <%= form.text_field :first_name, class: 'form-control' -%>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="form-group">
          <label class="control-label">Middle Name</label>
          <%= form.text_field :middle_name, class: 'form-control' -%>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="form-group">
          <label class="control-label">Last Name</label>
          <%= form.text_field :last_name, class: 'form-control' -%>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="form-group">
          <label class="control-label">Medical Record #</label>
          <%= form.text_field :medical_record, class: 'form-control' -%>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="form-group">
          <label class="control-label">Birth Date</label>
          <div class="birth-date-dropdowns">
            <%= form.date_select :birth_date, { end_year: Date.current.year - 80, start_year: Date.current.year - 18, prompt: true }, class: 'form-control' -%>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="form-group">
          <label class="control-label">Gender</label>
          <%= form.collection_select :gender, Patient.genders.keys, :to_s, :titlecase, { include_blank: 'Select an option' }, class: 'form-control' %>
        </div>
      </div>
    </div>

    <hr>

    <%= form.submit t('basic.forms.submit_save'), data: { disable_with: t('basic.forms.saving') }, class: 'btn btn-primary' -%>
    <%= link_to 'Delete', patient_path(patient), method: :delete, data: { disable_with: t('basic.forms.deleting'), confirm: t('basic.forms.confirm') }, class: 'btn btn-danger' unless patient.id.nil? -%>
    <% end %>
  </div>
</div>

app/views/patients/_list.html.erb
<div class="table-responsive">
  <% if !patients.blank? && patients.length > 0 -%>
  <table class="table table-hover m-t-10">
    <thead>
      <tr>
        <th width="5%">ID</th>
        <th width="20%">NAME</th>
        <th width="20%">AGE</th>
        <th width="20%">MEDICAL RECORD #</th>
        <th width="20%">DATE</th>
        <th width="5%"></th>
      </tr>
    </thead>
    <tbody>
      <% for patient in patients -%>
      <tr>
        <td><%= patient.id -%></td>
        <td><%= patient.full_name -%></td>
        <td><%= patient.age -%></td>
        <td><strong><%= patient.medical_record -%></strong></td>
        <td><%= l(patient.created_at, format: :complete) -%></td>
        <td><%= link_to 'View summary', summary_path(patient), class: 'btn btn-xs btn-primary' -%></td>
      </tr>
      <% end -%>
    </tbody>
  </table>
  <% else -%>
  <div class="alert alert-primary m-t-10" role="alert">No patients were found.</div>
  <% end -%>
</div>

app/views/patients/edit.html.erb
<div class="row">
  <div class="col-md-10 col-lg-10 col-sm-10">
    <h3 class="m-0">Edit patient: <%= @patient.full_name -%></h3>
    <hr>
    <%= render 'patients/form', patient: @patient, url: patient_path(@patient), method_type: :patch, remote: false -%>
    <hr>
  </div>
</div>

app/views/patients/index.html.erb
<div class="row">
  <div class="col-md-12 col-lg-12 col-sm-12">
    <h3 class="m-0">Patients List</h3>
    <hr>
    <%= render 'patients/list', patients: @patients -%>
  </div>
</div>

app/views/patients/new.html.erb
<div class="row">
  <div class="col-md-8 col-lg-8 col-sm-8">
    <div>
      <h3 class="m-0">Create new patient</h3>
      <hr>
      <%= render 'patients/form', patient: @patient, url: :patients, method_type: :post, remote: false -%>
      <hr>
    </div>
  </div>
</div>

app/views/patients/summary.html.erb
<table class="table table-bordered">
  <thead>
    <th class="active" colspan="4">Emergency Transfer Summary (Form 34L-D)</th>
  </thead>
  <tbody>
    <tr>
      <td colspan="4"><strong>Transferring Facility</strong></td>
    </tr>
    <tr>
      <td colspan="4">
        <p><strong>Name</strong></p>
        <p><%= @facility.name -%></p>
      </td>
    </tr>
    <tr>
      <td colspan="4"><strong>Patient Information</strong></td>
    </tr>
    <tr>
      <td>
        <p><strong>First Name</strong></p>
        <p><%= @patient.first_name -%></p>
      </td>
      <td>
        <p><strong>Middle Name</strong></p>
        <p><%= @patient.middle_name -%></p>
      </td>
      <td>
        <p><strong>Last Name</strong></p>
        <p><%= @patient.last_name -%></p>
      </td>
      <td>
        <p><strong>Medical Record (MR)</strong></p>
        <p><%= @patient.medical_record -%></p>
      </td>
    </tr>
    <tr>
      <td colspan="4"><strong>Summary</strong></td>
    </tr>
    <tr>
      <td colspan="4">
        <%= render_patient_summary(@facility, @patient) -%>
      </td>
    </tr>
  </tbody>
</table>

<div id="actions">
  <hr>
  <%= link_to 'Go Back', :patients, class: 'btn btn-sm btn-primary' -%>
  <%= link_to 'Print', '#', class: 'btn btn-sm btn-success', onclick: 'window.print();return false;' %>
</div>